### ISSUE TITLE
Support initial network time

### ISSUE THREAD

**Issue by francoischalifour** [antoinechalifour/memento#10]
When building apps, a challenging part is not getting a network response straight away. Responses often comes with random delays because network conditions are unstable. Getting responses from actual network conditions in development is an interesting feature because it would allow to design apps with high fidelity conditions: loading states, low-network resilience, flashes, etc.

This is a proposal to support initial network time.

## Storing network time in the response

Right now, the response format contains:

- Status code
- Headers
- Response

We could store some metadata in the cache, including the network time:

- Status code
- Headers
- Response
- Metadata
  - Network time

Here is the network information available in the Chrome Dev Tools Network panel:

![Network panel](https://user-images.githubusercontent.com/6137112/63094005-6fd0c380-bf67-11e9-9378-1eade846808c.png)

[See explanation](https://developers.google.com/web/tools/chrome-devtools/network/reference#timing-explanation)

## Possible implementation

1. Get this information from the network response
2. Compute the time the network request took in the Node process (e.g. using [Performance Timing API](https://nodejs.org/api/perf_hooks.html)) 

## Bailing out of this feature

We can introduce a new option (e.g. `skipDelays`) that ignores the delays and returns the response straight away.

IMO network time should be respected by default.

**Comment by antoinechalifour** [comment]
This is indeed a very useful feature. We should be able to implement it easely after #11 is merged
