### ISSUE TITLE
Support Multiple Target URLs

### ISSUE THREAD

**Issue by rkesters** [antoinechalifour/memento#123]
Covert the type of targetURL to 
```
targetURL: string | TargetUrlwithPort[];

interface TargetUrlwithPort {
  targetURL: string
 listenOn: number
}
```

If the config use the array version the `port` config is ignored and memento listens on each of the `listenPorts`.

The rationale for this is that many apps access multiple remote API, hence having one instance of Memento to handle all of them would be very helpful.

**Comment by antoinechalifour** [comment]
I'm not sure I understand. You want to launch Memento once, but listen on multiple ports to redirect to multiple target urls ?

I workaround for now is to launch multiple Memento instances.
