### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by antoinechalifour** [antoinechalifour/memento#3]

**Comment by maritaria** [comment]
I'm having an issue with CORS

Browser: Firefox 68
Axios (npm package): 0.17.1

Console output:
![image](https://user-images.githubusercontent.com/5500669/63928802-8e978580-ca50-11e9-9372-299faf1861ad.png)

**Comment by antoinechalifour** [comment]
Hi @maritaria ,

Can you send me a `.mementorc` configured so that I can investigate this issue ?

**Comment by maritaria** [comment]
I had only set a target url, no other settings.

**Comment by antoinechalifour** [comment]
For some reason its working on my end:

![image](https://user-images.githubusercontent.com/6087868/64063263-6b0c4080-cbf2-11e9-8317-12b3b7daa4e4.png)


Not sure how I can investigate further. What was your targetUrl ?

**Comment by maritaria** [comment]
An in-house api, I will ask our backend dev what the stack is for a small
reproduction
