### ISSUE TITLE
Requests fail when URL is too long

### ISSUE THREAD

**Issue by sadimusi** [antoinechalifour/memento#30]
Requests fail with HTTP status 500 and the following line in the memento log:
```
Error: ENAMETOOLONG: name too long, mkdir '/path/to/memento/.memento-cache/https___host/get__really_long_url?with=some&query=parameters'
```
In this case, the length of the entire URI was just 275 characters.

A suggestion: Use a (reasonably long) hash of the URL to generate the folder names. Or just truncate it, if fast lookup on the filesystem is not a requirement.

**Comment by antoinechalifour** [comment]
Nice catch! I'll try and publish a fix tonight

**Comment by antoinechalifour** [comment]
Alright @sadimusi, I just opened #31  that will fix this issue. I do not have time to release the fix today, but you can have a look and I'll merge it by tomorrow. Thanks a lot for reporting this bug 😉

**Comment by sadimusi** [comment]
Thanks a lot for the quick response! :+1: Great to see an active open source project :)
