### ISSUE TITLE
bug: when some chars in url that cant be in path it result in error

### ISSUE THREAD

**Issue by aldarund** [antoinechalifour/memento#49]
Error: C:\Dev\PycharmProjects\StampinUp.Ordering.Frontend\.memento-cache\https___qa-ordering-backend-stampinup-qa\get__en-us_products?-6d13f02e3ed5c6b7e9d0b8210aa77464b7900949 contains invalid WIN32 path characters.
      at Object.mkdirs (C:\Users\aldarund\AppData\Roaming\npm-cache\_npx\17460\node_modules\@antoinechalifour\memento\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18:22)

**Comment by antoinechalifour** [comment]
Hi @aldarund , thanks for reporting the issue.

I found this about invalid characters: [fs-extra source code](https://github.com/jprichardson/node-fs-extra/blob/master/lib/mkdirs/win32.js), [Windows rules for directory names](https://stackoverflow.com/questions/62771/how-do-i-check-if-a-given-string-is-a-legal-valid-file-name-under-windows/62888#62888).

I can fix it but won't be able to try it on an actual computer as I don't have access to a Windows machine.

**Comment by aldarund** [comment]
if u create PR, i can test it locallt

**Comment by antoinechalifour** [comment]
Sure, Ill try to fix it by tomorrow

**Comment by antoinechalifour** [comment]
Hi @aldarund , I just opened #57 . It would be great if you could test it locally and give me some feedback :)

**Comment by antoinechalifour** [comment]
I just release 1.3.1-alpha.0 which includes the fix. You may try it using: `npx @antoinechalifour/memento@1.3.1-alpha.0`

Let me know if it works!

**Comment by aldarund** [comment]
@antoinechalifour just got to it. 1.5 seems to work fine
