### ISSUE TITLE
Add mode to disable caching

### ISSUE THREAD

**Issue by maritaria** [antoinechalifour/memento#54]
I would like to keep my development env as simple as possible and thus always route all traffic through memento. If I temporarily dont want to use. memento it would be easiest if I could just edit the memento config or issue a memento command (rather than edit my configs of the app)

**Comment by antoinechalifour** [comment]
Memento definitely needs this feature! I was thinking I could an option to the configuration like this

```
{
  // other config
  "disableCaching": "<REGEXP>"
}
```

Using a syntax ["à la Jest"](https://jestjs.io/docs/en/configuration#transformignorepatterns-array-string). What do you think ?

**Comment by antoinechalifour** [comment]
Hi @maritaria ,

I just opened #56 which implements this functionality. Here is the new documentation for this branch, if you want to have a look: https://github.com/antoinechalifour/memento/tree/disable-caching

It would be great to have some feedback from you before releasing this feature.

Thanks!
